[package]
name = "cheat_sheet"
version = "0.1.1"
authors = ["kernel-dev <nbelsito02@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# adding an external crate to the package
rand = "0.7.3"
